### ISSUE TITLE
Syntax error when transpiling babel code

### ISSUE THREAD

**Issue by as-cii** [MoritzKn/atom-autocomplete-jsp#1]
In the process of upgrading babel in Atom core (https://github.com/atom/atom/pull/13823) we have noticed this package doesn't transpile correctly. In particular, we have found the following errors:

* `autocomplete-jsp/src/tag-provider.js: Unexpected token, expected , (139:5)`
* `autocomplete-jsp/src/utils.js: Unexpected token, expected , (39:1)`

To ensure your package keeps working after we will merge and release the aforementioned pull request, please make sure to fix these errors and publish a new version.

Please, let me know if you have any questions or concerns and if I can help somehow. Thanks!

**Comment by MoritzKn** [comment]
@as-cii thanks for informing me upfront!
