### ISSUE TITLE
Does this package autocomplete core JSTL tags?

### ISSUE THREAD

**Issue by williamtguerra** [MoritzKn/atom-autocomplete-jsp#2]
ex: `<c:choose>`

doesn't seem like its included. or perhaps do you know another package that already does this?

**Comment by MoritzKn** [comment]
It does! but you need to download the TLD file and alter the `tldSources` setting to include the directory you placed the TLD File in. See [setup](https://github.com/MoritzKn/atom-autocomplete-jsp#setup) for details on how to get the JSTL TLD files etc.
Beside that I don't really know any other package adding JSP related features what so ever.
Let me know if you have trouble getting it working.

**Comment by williamtguerra** [comment]
thanks for the response. I must have not performed the setup correctly then

I've tried both adding the TLDs into the default `.atom/...` directory and a separate directory while ensuring the `tldSources` was pointing to the correct folder. I then restarted with no noticeable changes. when I begin to type `cif` or `if` I just see other html autocomplete suggestions like `iframe`

I downloaded the TLD files from the wget commands linked in the setup, and restarted the editor. any other ideas I may be forgetting?

**Comment by MoritzKn** [comment]
What version of this package do you use? I've added support for tag completion with version v1.0.0

**Comment by williamtguerra** [comment]
currently 1.0.1
here is a screenshot of the config, and tld directory

![image](https://cloud.githubusercontent.com/assets/3419227/23173144/cd4e7c8c-f81d-11e6-82dd-b9920fe667a9.png)

**Comment by MoritzKn** [comment]
Well, so far looks all right for me... I will do a bit of testing and debugging. I will also rework this to make it easier to use.

**Comment by williamtguerra** [comment]
I appreciate the effort

**Comment by MoritzKn** [comment]
>  I appreciate the effort  

Nah, I want this package to be usable. 


But I may have missed a major point here.. to get completion for taglibs you need to import them first. This can be done in a few different ways:
* By using a taglib Directive:
```jsp
<%@ taglib uri="http://example.com/uri/of/the/taglib" prefix="prefixOfTag" >
```
*  Or it's XML equivalent:
```jsp
<jsp:directive.taglib uri="http://example.com/uri/of/the/taglib" prefix="prefixOfTag" />
```
* Or by a XML namespace delectation:
```jsp
<anyxmlelement xmlns:prefixOfTag="http://example.com/uri/of/the/taglib">
```
So for the core lib this would be:
```jsp
<html xmlns:c="http://java.sun.com/jsp/jstl/core">
    <c:choo <!-- get auto completion here -->
```
More details on that:
* http://www.tutorialspoint.com/jsp/taglib_directive.htm
* http://stackoverflow.com/tags/jstl/info

As far as I know importing the taglib is required by JSP so it makes sense to only autocomplete imported taglibs. If there is a exception to this I am not aware of, please tell me.

**Comment by williamtguerra** [comment]
for the project I'm trying this on there is a common taglib `<%@ include %>` imported into every jsp.  
that said, even inside of that file I couldn't trigger it


![image](https://cloud.githubusercontent.com/assets/3419227/23189108/05439aa8-f857-11e6-9f58-0deec2a27a54.png)

**Comment by MoritzKn** [comment]
Dammit, I thought that would be it. But only `c` is not enough as prefix for this package you need to use something like `<c:choo` or `<c` and press <kbd>shift-space</kbd>.

**Comment by williamtguerra** [comment]
ah ok

1. did not know it needed the `<` character, thats why I wasn't getting it to show. I only tried `choo...` and `c:choo...`

2. it pretty much only works in that taglib import file since the taglibs are referenced indirectly throughout the rest of the project

I think we can close this

**Comment by MoritzKn** [comment]
> since the taglibs are referenced indirectly throughout the rest of the project

Wait, that is possible? That would make the way this package handles imports pretty stupid. Could you explain how this works or point me to some online resource?

**Comment by williamtguerra** [comment]
throughout the project we have `<%@ include file="/WEB-INF/jsp/common/taglibs.jsp" %>` at the top of every jsp/tag

that references the core JSTL taglibs as shown in the screenshot I posted above, as well as our own custom source files below. its just a file full of `<%@ taglib >`'s essentially

**Comment by MoritzKn** [comment]
Ok thanks, I wasn't aware this was possible. At my company we only use the XML namespace form. Maybe I can implement something that follows imports of other JSP files to find all taglib imports.

**Comment by MoritzKn** [comment]
I added a mechanism to follow include directives to find all declared taglibs, so with version v1.1.0 this should work now. 🎉

**Comment by williamtguerra** [comment]
getting the following console error right after typing `<c:i`

```
find-declared-taglibs.js [sm]:149
Error reading included file /WEB-INF/jsp/common/taglibs.jsp: Error: ENOENT: no such file or directory, open '/WEB-INF/jsp/common/taglibs.jsp'(…)
(anonymous function) @ find-declared-taglibs.js [sm]:149
```

my guess is it is possibly trying to search the relative path as an absolute path?

**Comment by MoritzKn** [comment]
As far as I can tell according to the [spec](http://download.oracle.com/otn-pub/jcp/jsp-2_3-mrel2-eval-spec/JSP2.3MR.pdf) (Section JSP.1.10.3) the path of a include directive must be relative. But I think resolving absolute paths relative to the webapp folder should be possible anyway.

**Comment by MoritzKn** [comment]
OK, absolute paths are now (`v1.2.0`) resolved relative to the webapp directory. To find the webapp directory it basically scans the path of the file including the file for `src/*/*`. This means all paths like those will work: 
* `/home/foo/workspace/foo/src/main/webapp/bar/baz/` resolves to `/home/foo/workspace/foo/src/main/webapp/`
* `/foo/src/test/webapp/foo/src/bar` resolves to `/foo/src/test/webapp/`
* `/foo/src/bar/resources/bar/test` resolves to `/foo/src/bar/resources/`

**Comment by williamtguerra** [comment]
niiiice. works great 😄

**Comment by MoritzKn** [comment]
Perfect! Feel free to report new issues if you encounter other problems.
